---
- hosts: all
  remote_user: admin
  become_user: root
  become_method: su

  vars:
    site_url: publishwhatyoufund.org

  vars_files:
   - playbook_vars/pwyforg.yml

  roles:
   - common
   - php_mysql
   - wordpress
