---
- name: Create MySQL database
  mysql_db: name={{ mysql_db }} state=present
  become: true

- name: Create MySQL user
  mysql_user: name={{ mysql_user }} password="{{ mysql_pwd }}" priv={{ mysql_db }}.*:ALL host='localhost' state=present
  become: true

- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive:
    src=/tmp/wordpress.tar.gz
    dest=/tmp/
    copy=no

- name: Move WordPress into place
  synchronize:
    src=/tmp/wordpress/
    dest=/var/www/{{ site_path }}/
    archive=yes
    delete=yes
  delegate_to: "{{ inventory_hostname }}"
  become: true

- name: Change ownership of WordPress installation
  file: path=/var/www/{{ site_path }}/ owner={{ user }} group=www-data state=directory recurse=yes setype=httpd_sys_content_t
  become: true

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: Copy WordPress config file
  template: src=wp-config.php.j2 dest=/var/www/{{ site_path }}/wp-config.php owner={{ user }} group=www-data
  become: true

- name: Create apache site config
  template: src=apache.conf.j2 dest=/etc/apache2/sites-available/{{ site_url }}.conf
  become: true

- name: Enable {{ site_url }} apache site
  command: a2ensite {{ site_url }}.conf
  notify:
   - restart apache
  become: true
